const ACTIVITIES=[
['Spacer','🚶'],['Spacer z psem','🐕'],['Rower','🚲'],['Hulajnoga','🛴'],['Rolki','🛼'],['Deskorolka','🛹'],['Basen','🏊'],['Bieganie','🏃'],['Marsz','🥾'],['Piłka nożna','⚽'],['Koszykówka','🏀'],['Siatkówka','🏐'],['Tenis','🎾'],['Badminton','🏸'],['Tenis stołowy','🏓'],['Judo','🥋'],['Karate','🥋'],['Taniec','💃'],['Gimnastyka','🤸'],['Ćwiczenia w domu','🏠'],['SKS','🏫'],['Trening klubowy','🏅'],['Plac zabaw','🛝'],['Zabawa na podwórku','🌳'],['Trampolina','🤸'],['Wspinaczka','🧗'],['Park linowy','🌲'],['Wycieczka piesza','🥾'],['Góry','⛰️'],['Narty','⛷️'],['Snowboard','🏂'],['Łyżwy','⛸️'],['Kajak','🛶'],['Żagle','⛵'],['Frisbee','🥏'],['Rzutki / celność','🎯'],['Gra terenowa','🧭'],['Zabawy ruchowe','🎈'],['Rozciąganie','🧘'],['Inna aktywność','➕']
];
const KEY='aktywnik-plus-data-v1';
const defaultState={favorites:['Spacer','Rower','Hulajnoga','Basen','Piłka nożna'],entries:[],rewards:[],reminderHour:19,reminderMinute:30,school:{mode:'hybrid',requireParentApproval:true,useEffort:true,usePluses:true,gradeRule:'manual',maxCountedMinutes:null}};
let state=load(); let selected=null; let reportType='month';
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function fmtMin(m){const h=Math.floor(m/60),r=m%60;return h?`${h} h${r?` ${r} min`:''}`:`${r} min`}
function today(){return new Date().toISOString().slice(0,10)}
function pickActivity(name){selected=name;$('#selectedActivityTitle').textContent=name;$('#activityDate').value=today();$('#entryCard').classList.remove('hidden');$('#entryCard').scrollIntoView({behavior:'smooth',block:'center'})}
function activityButton([name,emoji]){const b=document.createElement('button');b.className='activity';b.innerHTML=`<span class="emoji">${emoji}</span>${name}`;b.onclick=()=>pickActivity(name);return b}
function renderActivities(){const fav=$('#favoriteActivities');fav.innerHTML='';ACTIVITIES.filter(a=>state.favorites.includes(a[0])).forEach(a=>fav.append(activityButton(a)));const q=$('#activitySearch').value.toLowerCase();const all=$('#allActivities');all.innerHTML='';ACTIVITIES.filter(a=>a[0].toLowerCase().includes(q)).forEach(a=>all.append(activityButton(a)))}
function saveEntry(){const minutes=Number($('#activityDuration').value);if(!selected||!minutes||minutes<1)return;state.entries.unshift({id:crypto.randomUUID(),date:$('#activityDate').value||today(),activity:selected,minutes,effort:Number($('#activityEffort').value),note:$('#activityNote').value.trim(),status:'pending',createdAt:new Date().toISOString()});selected=null;$('#activityNote').value='';$('#entryCard').classList.add('hidden');persist()}
function statusLabel(e){return e.status==='approved'?'<span class="status-approved">✓ zatwierdzone</span>':'<span class="status-pending">⏳ czeka na rodzica</span>'}
function renderChildEntries(){const box=$('#childEntries');box.innerHTML='';state.entries.slice(0,12).forEach(e=>{const el=document.createElement('div');el.className='entry';el.innerHTML=`<div><strong>${e.activity} · ${fmtMin(e.minutes)}</strong><small>${e.date} · wysiłek ${e.effort}/5${e.note?` · ${escapeHtml(e.note)}`:''}<br>${statusLabel(e)}</small></div>`;box.append(el)});if(!state.entries.length)box.innerHTML='<small>Jeszcze nie ma wpisów.</small>';const pending=state.entries.filter(e=>e.status==='pending').length;$('#pendingChildBadge').textContent=pending?`${pending} do zatwierdzenia`:'';$('#todayMinutes').textContent=state.entries.filter(e=>e.date===today()).reduce((s,e)=>s+e.minutes,0)}
function approve(id){const e=state.entries.find(x=>x.id===id);if(e)e.status='approved';persist()}
function removeEntry(id){state.entries=state.entries.filter(x=>x.id!==id);persist()}
function renderApprovals(){const p=state.entries.filter(e=>e.status==='pending');$('#pendingCount').textContent=p.length;const list=$('#approvalList');list.innerHTML='';p.forEach(e=>{const el=document.createElement('div');el.className='entry';el.innerHTML=`<div><strong>${e.activity} · ${fmtMin(e.minutes)}</strong><small>${e.date} · wysiłek ${e.effort}/5${e.note?` · ${escapeHtml(e.note)}`:''}</small></div><div class="entry-actions"><button class="primary" data-approve="${e.id}">Akceptuj</button><button class="ghost" data-remove="${e.id}">Usuń</button></div>`;list.append(el)});if(!p.length)list.innerHTML='<small>Wszystko zatwierdzone.</small>';$$('[data-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.approve));$$('[data-remove]').forEach(b=>b.onclick=()=>removeEntry(b.dataset.remove));const n=new Date(),after=n.getHours()>state.reminderHour||(n.getHours()===state.reminderHour&&n.getMinutes()>=state.reminderMinute);$('#approvalReminder').classList.toggle('hidden',!(after&&p.length))}
function startFor(type,d=new Date()){const y=d.getFullYear(),m=d.getMonth();if(type==='month')return new Date(y,m,1);if(type==='quarter')return new Date(y,Math.floor(m/3)*3,1);if(type==='half')return new Date(y,m<6?0:6,1);return new Date(y,0,1)}
function filtered(type){const start=startFor(type);return state.entries.filter(e=>e.status==='approved'&&new Date(e.date+'T12:00:00')>=start)}
function stats(type){const es=filtered(type),minutes=es.reduce((s,e)=>s+e.minutes,0),days=new Set(es.map(e=>e.date)).size,types=new Set(es.map(e=>e.activity)).size;const counts={};es.forEach(e=>counts[e.activity]=(counts[e.activity]||0)+e.minutes);return {es,minutes,days,types,counts}}
function renderStats(){const s=stats($('#reportPeriod').value);$('#statsGrid').innerHTML=`<div class="stat"><strong>${fmtMin(s.minutes)}</strong><small>łączny czas</small></div><div class="stat"><strong>${s.days}</strong><small>aktywne dni</small></div><div class="stat"><strong>${s.es.length}</strong><small>aktywności</small></div><div class="stat"><strong>${s.types}</strong><small>różne rodzaje</small></div>`;const max=Math.max(1,...Object.values(s.counts));$('#activityBreakdown').innerHTML=Object.entries(s.counts).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([n,v])=>`<div class="bar-row"><span>${n}</span><div class="bar"><i style="width:${Math.round(v/max*100)}%"></i></div><strong>${fmtMin(v)}</strong></div>`).join('')||'<small>Statystyki pojawią się po zatwierdzeniu aktywności.</small>'}
function reportTitle(t){return ({month:'Raport miesięczny',quarter:'Raport kwartalny',half:'Raport półroczny',year:'Raport roczny'})[t]}
function renderParentReport(){const s=stats(reportType);$('#parentReport').innerHTML=`<div class="parent-only-print"><h2>${reportTitle(reportType)} — Aktywnik+</h2><p><strong>Łączny czas:</strong> ${fmtMin(s.minutes)} · <strong>Aktywne dni:</strong> ${s.days} · <strong>Liczba aktywności:</strong> ${s.es.length} · <strong>Różne rodzaje:</strong> ${s.types}</p><div class="list">${s.es.map(e=>`<div class="entry"><div><strong>${e.date} — ${e.activity}</strong><small>${fmtMin(e.minutes)} · wysiłek ${e.effort}/5${e.note?` · ${escapeHtml(e.note)}`:''}</small></div></div>`).join('')||'<small>Brak zatwierdzonych wpisów w tym okresie.</small>'}</div><h3>Uwagi rodzica</h3><p>....................................................................................................</p><h3>Uwagi nauczyciela / wychowawcy</h3><p>....................................................................................................</p><p>....................................................................................................</p></div>`}
function renderFavoritesEditor(){const box=$('#favoritesEditor');box.innerHTML='';ACTIVITIES.forEach(([name,emoji])=>{const l=document.createElement('label');l.innerHTML=`<input type="checkbox" ${state.favorites.includes(name)?'checked':''} data-fav="${name}"> ${emoji} ${name}`;box.append(l)});$$('[data-fav]').forEach(c=>c.onchange=()=>{if(c.checked&&!state.favorites.includes(c.dataset.fav))state.favorites.push(c.dataset.fav);if(!c.checked)state.favorites=state.favorites.filter(x=>x!==c.dataset.fav);persist();renderFavoritesEditor()})}
function switchMode(mode){const child=mode==='child',parent=mode==='parent',school=mode==='school';$('#childPanel').classList.toggle('hidden',!child);$('#parentPanel').classList.toggle('hidden',!parent);$('#schoolPanel').classList.toggle('hidden',!school);$('#childModeBtn').classList.toggle('active',child);$('#parentModeBtn').classList.toggle('active',parent);$('#schoolModeBtn').classList.toggle('active',school)}
function renderSchoolSettings(){const c=state.school||defaultState.school;$('#schoolMode').value=c.mode;$('#requireParentApproval').value=c.requireParentApproval?'yes':'no';$('#useEffort').value=c.useEffort?'yes':'no';$('#usePluses').value=c.usePluses?'yes':'no';$('#gradeRule').value=c.gradeRule||'manual';$('#maxCountedMinutes').value=c.maxCountedMinutes??'';$('#rewardDate').value=$('#rewardDate').value||today();const box=$('#rewardHistory');box.innerHTML='';[...(state.rewards||[])].sort((a,b)=>b.date.localeCompare(a.date)).forEach(r=>{const el=document.createElement('div');el.className='entry';el.innerHTML=`<div><strong>${r.type==='plus'?'Plus':'Ocena'} · ${escapeHtml(r.value)}</strong><small>${r.date}${r.note?` · ${escapeHtml(r.note)}`:''}</small></div>`;box.append(el)});if(!(state.rewards||[]).length)box.innerHTML='<small>Brak zapisanych plusów i ocen.</small>'}
function saveSchoolSettings(){state.school={mode:$('#schoolMode').value,requireParentApproval:$('#requireParentApproval').value==='yes',useEffort:$('#useEffort').value==='yes',usePluses:$('#usePluses').value==='yes',gradeRule:$('#gradeRule').value,maxCountedMinutes:$('#maxCountedMinutes').value?Number($('#maxCountedMinutes').value):null};persist()}
function saveReward(){const value=$('#rewardValue').value.trim();if(!value)return;state.rewards=state.rewards||[];state.rewards.unshift({id:crypto.randomUUID(),type:$('#rewardType').value,value,date:$('#rewardDate').value||today(),note:$('#rewardNote').value.trim(),createdAt:new Date().toISOString()});$('#rewardValue').value='';$('#rewardNote').value='';persist()}
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderAll(){renderActivities();renderChildEntries();renderApprovals();renderStats();renderParentReport();renderSchoolSettings()}
$('#activitySearch').oninput=renderActivities;$('#saveEntryBtn').onclick=saveEntry;$('#cancelEntryBtn').onclick=()=>$('#entryCard').classList.add('hidden');$('#childModeBtn').onclick=()=>switchMode('child');$('#parentModeBtn').onclick=()=>switchMode('parent');$('#schoolModeBtn').onclick=()=>switchMode('school');$('#saveSchoolSettingsBtn').onclick=saveSchoolSettings;$('#saveRewardBtn').onclick=saveReward;$('#reportPeriod').onchange=renderStats;$('#approveAllBtn').onclick=()=>{state.entries.forEach(e=>{if(e.status==='pending')e.status='approved'});persist()};$('#editFavoritesBtn').onclick=()=>{renderFavoritesEditor();$('#favoritesDialog').showModal()};$$('[data-report]').forEach(b=>b.onclick=()=>{reportType=b.dataset.report;renderParentReport()});$('#printReportBtn').onclick=()=>window.print();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderAll();